name: Compilar APK Radar Esportivo

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do projeto
        uses: actions/checkout@v4

      - name: Compilar APK usando Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer -v android debug
          buildozer_version: stable

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: RadarEsportivo-APK
          path: ./*.apk
